import Head from 'next/head';
import { Barnner } from '../components/Barnner';
import { Footer } from '../components/Footer';
import { Header } from '../components/Header';
import { LargeCard } from '../components/LargeCard';
import { MediumCard } from '../components/MediumCard';
import { SmallCard } from '../components/SmallCard';
// import styles from '../styles/Home.module.css'

export default function Home({exploreData, cardData}) {
  return (
    <div className=''>
      <Head>
        <title>airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* header */}
      <Header />

      {/* Banner */}
      <Barnner />
     <main className='max-w-7xl mx-auto px-8 sm:px-16'>
       <section className='pt-6'>
         <h2 className='text-4xl font-semibold  pb-5'>Explore Nearby</h2>
         <div className='grid lg:grid-cols-4 md:grid-cols-3 sm:grid-cols-2'>
         {
           exploreData.map((item,i)=>(
              <SmallCard key={i} img={item.img} location={item.location} distance={item.distance} />
           ))
         }
         </div>
       </section>

       <section>
         <h2 className="text-4xl font-semibold py-8">Live anywhere</h2>
         <div>
         <div className='flex space-x-3 overflow-scroll scrollbar-hide p-3 hover:scroll-auto scroll-smooth'>
         {
             cardData.map((item, i)=>(
              <MediumCard key={i} img={item.img} title={item.title} />
            ))
          }
         </div>
         </div>
       </section>

       <section>
         <LargeCard
         img="https://links.papareact.com/4cj"
         title="The Greatest Outdoors"
         description ="Whirlists curated by Airbnb"
         buttonText = " Get Inspired"
          />
       </section>
     </main>

     <footer> 
       <Footer />
     </footer>
    </div>
  )
}

export async function getStaticProps (){
  const exploreData =  await fetch('https://links.papareact.com/pyp')
  .then(res=> res.json());

  const cardData = await fetch('https://links.papareact.com/zp1')
  .then(res=>res.json());
  return{
    props:{
      exploreData,
      cardData
    }
  }
}


